
en:
  mapping: 'naturalearth_lowres'
  terms: ['covid19', '#ncov2019', 'Covid_19', '#conronaviruspandemic', 'COVID-19', '#caronavirus', '#infocoronavirus', 'coronavirusupdate', 'carona virus', '#coronavirues', '#Coronovirus', '#2019nCoV', '#Coronvirus', '#Coronavirus', 'covid-19', 'Coronavirus', '#caronavirusoutbreak', 'covid', '#CoronaVirusUpdate', '#Corvid19virus', '#covid', 'coronavirus', '#CoronaVirus', 'nCoV', 'covid 19', '#nCoV2019', '#covid_19', '#coronavirusupdates', '#COVIDー19', '#2019nCov', '#CoronaAlert', '#coronavirus', 'SARS-CoV-2', '#nCoV', '#coronanews', '#COVID', '2019nCoV', '#CoronavirusOutbreak', '#coronapocolypse', '#COVID19', '#codvid19', '#codvid_19', 'coronavirus outbreak']
  path: "../tweets/en/"
  csv_size: 1000000
  update_data_size: 1000
  stream_all: False
  image_dir: images
  image_path: smsearch_gl.png
  hash_addresses_dir: addresses
  hash_addresses_path: addresses_gl.csv

el:
  mapping: 'naturalearth_lowres'
  terms: ['covid19', '#ncov2019', 'Covid_19', '#conronaviruspandemic', 'COVID-19', '#caronavirus', '#infocoronavirus', 'coronavirusupdate', 'carona virus', '#coronavirues', '#Coronovirus', '#2019nCoV', '#Coronvirus', '#Coronavirus', 'covid-19', 'Coronavirus', '#caronavirusoutbreak', 'covid', '#CoronaVirusUpdate', '#Corvid19virus', 'coronavirus', '#covid', '#CoronaVirus', 'nCoV', 'κοροναιος', 'covid 19', '#nCoV2019', '#covid_19', '#coronavirusupdates', '#COVIDー19', '#2019nCov', '#CoronaAlert', '#coronavirus', 'SARS-CoV-2', '#nCoV', 'κορονοιος', 'κορωνοιος', '#coronanews', '#COVID', '2019nCoV', '#CoronavirusOutbreak', '#coronapocolypse', 'κορωναιος', '#COVID19', '#codvid19', '#codvid_19', 'coronavirus outbreak']
  path: "../tweets/el/"
  csv_size: 1000000
  update_data_size: 10
  stream_all: True
  image_dir: images
  image_path: smsearch_el.png
  hash_addresses_dir: addresses
  hash_addresses_path: addresses_el.csv

sv:
  mapping: 'naturalearth_lowres'
  terms: ['covid19', '#ncov2019', 'Covid_19', '#conronaviruspandemic', 'COVID-19', '#caronavirus', '#infocoronavirus', 'coronavirusupdate', 'carona virus', '#coronavirues', '#Coronovirus', '#2019nCoV', '#Coronvirus', '#Coronavirus', 'covid-19', 'Coronavirus', '#caronavirusoutbreak', 'covid', '#CoronaVirusUpdate', '#Corvid19virus', 'coronavirus', '#covid', '#CoronaVirus', 'nCoV', 'covid 19', '#nCoV2019', '#covid_19', '#coronavirusupdates', '#COVIDー19', '#2019nCov', '#CoronaAlert', '#coronavirus', '#nCoV', '#coronanews', '#COVID', '2019nCoV', '#CoronavirusOutbreak', '#coronapocolypse', '#COVID19', '#codvid19', '#codvid_19', 'coronavirus outbreak']
  path: "../tweets/se/"
  csv_size: 1000000
  update_data_size: 10
  stream_all: True
  image_dir: images
  image_path: smsearch_se.png
  hash_addresses_dir: addresses
  hash_addresses_path: addresses_se.csv

