
en:
  mapping: 'naturalearth_lowres'
  terms: ['covid-19', 'coronavirus', 'covid19']
  path: "../tweets/en/"
  csv_size: 1000000
  update_data_size: 1000
  stream_all: False
  image_dir: images
  image_path: smsearch_gl.png
  hash_addresses_dir: addresses
  hash_addresses_path: addresses_gl.csv

el:
  mapping: 'naturalearth_lowres'
  terms: ['covid-19', 'coronavirus', 'covid19', 'κορονοιος', 'κοροναιος', 'κορωνοιος', 'κορωναιος']
  path: "../tweets/el/"
  csv_size: 1000000
  update_data_size: 10
  stream_all: True
  image_dir: images
  image_path: smsearch_el.png
  hash_addresses_dir: addresses
  hash_addresses_path: addresses_el.csv



